name: cryptocurrency-viewer-frontend-deployment
on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_deployment.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git

      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix frontend master`:refs/heads/master --force
